using UnityEngine;

public class Parallax : MonoBehaviour
{
   public float parallaxFactor = 0.5f;

   public Transform cameraTransform;
   private Vector3 previousCameraPosition;

    private void Start()
    {
        if (cameraTransform == null)
       {
           cameraTransform = Camera.main.transform;
       }
       previousCameraPosition = cameraTransform.position;
    }

    private void LateUpdate()
    {
        Vector3 deltaMovement = cameraTransform.position - previousCameraPosition;
        transform.position += new Vector3(deltaMovement.x * parallaxFactor, deltaMovement.y * parallaxFactor, 0);
        previousCameraPosition = cameraTransform.position;
    }



}
